name: Python Flask App CI

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest playwright
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Playwright
        run: playwright install

      - name: Run Pytests and Playwright tests
        run: pytest -k "test_"
